
import { AuthInit } from "@/components/provider/AuthInit";
import QueryProvider from "@/components/provider/QueryClient";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <QueryProvider>
          <AuthInit />
          {children}
          <Toaster position="top-right" richColors />
        </QueryProvider>
      </body>
    </html>

  );
}
